apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smokeping-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    # cert-manager.io/issuer: "smokeping-issuer"
    traefik.ingress.kubernetes.io/redirect-entry-point: "https"
spec:
  rules:
    - host: {{ .Values.ingress.ingressDomain }}
      http:
        paths:
          - backend:
              service:
                name: smokeping
                port:
                  number: 80
            path: /
            pathType: Prefix
  # tls:
  #   - hosts:
  #     - {{ .Values.ingress.ingressDomain }}
  #     secretName: {{ .Values.issuer.secretName }}