# Default values for Smokeping.
# Update these values according to your requirements.
ingressHost: https://kubernetes.default.svc

influxdb:
  create: false
  image: sjultra/influxdb-legacy:latest
  adminUser: admin
  adminPassword: password
  db: smokeping

grafana:
  create: false
  image: grafana/grafana:10.1.2
  adminPassword: admin
  ROOTURL: "https://kubernetes.default.svc/api/v1/namespaces/smokeping/services/http:grafana:80/proxy/?orgId=1"
  port: 80

smokeping:
  image: sjultra/smokeping:latest
  port: 8080

issuer:
  issuerEmail: ops@sjultra.com
  secretName: smokeping-tls-prod
  privateKeyName: smokeping-tls-pkey-prod

ingress:
  ingressDomain: smokeping.yourdomain.com